---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/installation
  label: Installation
  create: all
  match: "**/*"
- type: directory
  path: content/successful
  label: Successful
  create: all
  match: "**/*"
- type: directory
  path: content/payments
  label: Payments
  create: all
  match: "**/*"
- type: directory
  path: content/connection
  label: Connection
  create: all
  match: "**/*"
- type: directory
  path: content/speed
  label: Speed
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
